// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc1
// source: pkg/pb/admin/admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminSignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Firstname     string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSignupRequest) Reset() {
	*x = AdminSignupRequest{}
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSignupRequest) ProtoMessage() {}

func (x *AdminSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSignupRequest.ProtoReflect.Descriptor instead.
func (*AdminSignupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_admin_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminSignupRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *AdminSignupRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *AdminSignupRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminSignupRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminSignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	AdminDetails  *AdminDetails          `protobuf:"bytes,2,opt,name=adminDetails,proto3" json:"adminDetails,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSignupResponse) Reset() {
	*x = AdminSignupResponse{}
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSignupResponse) ProtoMessage() {}

func (x *AdminSignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSignupResponse.ProtoReflect.Descriptor instead.
func (*AdminSignupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminSignupResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminSignupResponse) GetAdminDetails() *AdminDetails {
	if x != nil {
		return x.AdminDetails
	}
	return nil
}

func (x *AdminSignupResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminSignupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AdminDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname     string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname      string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDetails) Reset() {
	*x = AdminDetails{}
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDetails) ProtoMessage() {}

func (x *AdminDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDetails.ProtoReflect.Descriptor instead.
func (*AdminDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminDetails) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminDetails) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *AdminDetails) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *AdminDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AdminLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginRequest) Reset() {
	*x = AdminLoginRequest{}
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRequest) ProtoMessage() {}

func (x *AdminLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRequest.ProtoReflect.Descriptor instead.
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AdminLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	AdminDetails  *AdminDetails          `protobuf:"bytes,2,opt,name=adminDetails,proto3" json:"adminDetails,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminLoginResponse) Reset() {
	*x = AdminLoginResponse{}
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginResponse) ProtoMessage() {}

func (x *AdminLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginResponse.ProtoReflect.Descriptor instead.
func (*AdminLoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminLoginResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminLoginResponse) GetAdminDetails() *AdminDetails {
	if x != nil {
		return x.AdminDetails
	}
	return nil
}

func (x *AdminLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminLoginResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pb_admin_admin_proto protoreflect.FileDescriptor

const file_pkg_pb_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/pb/admin/admin.proto\x12\x05admin\"\x80\x01\n" +
	"\x12AdminSignupRequest\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x92\x01\n" +
	"\x13AdminSignupResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x127\n" +
	"\fadminDetails\x18\x02 \x01(\v2\x13.admin.AdminDetailsR\fadminDetails\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"n\n" +
	"\fAdminDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"E\n" +
	"\x11AdminLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x91\x01\n" +
	"\x12AdminLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x127\n" +
	"\fadminDetails\x18\x02 \x01(\v2\x13.admin.AdminDetailsR\fadminDetails\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\x94\x01\n" +
	"\x05Admin\x12F\n" +
	"\vAdminSignup\x12\x19.admin.AdminSignupRequest\x1a\x1a.admin.AdminSignupResponse\"\x00\x12C\n" +
	"\n" +
	"AdminLogin\x12\x18.admin.AdminLoginRequest\x1a\x19.admin.AdminLoginResponse\"\x00B\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_admin_admin_proto_rawDescOnce sync.Once
	file_pkg_pb_admin_admin_proto_rawDescData []byte
)

func file_pkg_pb_admin_admin_proto_rawDescGZIP() []byte {
	file_pkg_pb_admin_admin_proto_rawDescOnce.Do(func() {
		file_pkg_pb_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_admin_admin_proto_rawDesc), len(file_pkg_pb_admin_admin_proto_rawDesc)))
	})
	return file_pkg_pb_admin_admin_proto_rawDescData
}

var file_pkg_pb_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_pb_admin_admin_proto_goTypes = []any{
	(*AdminSignupRequest)(nil),  // 0: admin.AdminSignupRequest
	(*AdminSignupResponse)(nil), // 1: admin.AdminSignupResponse
	(*AdminDetails)(nil),        // 2: admin.AdminDetails
	(*AdminLoginRequest)(nil),   // 3: admin.AdminLoginRequest
	(*AdminLoginResponse)(nil),  // 4: admin.AdminLoginResponse
}
var file_pkg_pb_admin_admin_proto_depIdxs = []int32{
	2, // 0: admin.AdminSignupResponse.adminDetails:type_name -> admin.AdminDetails
	2, // 1: admin.AdminLoginResponse.adminDetails:type_name -> admin.AdminDetails
	0, // 2: admin.Admin.AdminSignup:input_type -> admin.AdminSignupRequest
	3, // 3: admin.Admin.AdminLogin:input_type -> admin.AdminLoginRequest
	1, // 4: admin.Admin.AdminSignup:output_type -> admin.AdminSignupResponse
	4, // 5: admin.Admin.AdminLogin:output_type -> admin.AdminLoginResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_pb_admin_admin_proto_init() }
func file_pkg_pb_admin_admin_proto_init() {
	if File_pkg_pb_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_admin_admin_proto_rawDesc), len(file_pkg_pb_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_admin_admin_proto_goTypes,
		DependencyIndexes: file_pkg_pb_admin_admin_proto_depIdxs,
		MessageInfos:      file_pkg_pb_admin_admin_proto_msgTypes,
	}.Build()
	File_pkg_pb_admin_admin_proto = out.File
	file_pkg_pb_admin_admin_proto_goTypes = nil
	file_pkg_pb_admin_admin_proto_depIdxs = nil
}
