// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc1
// source: pkg/pb/product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductRequest) Reset() {
	*x = CheckProductRequest{}
	mi := &file_pkg_pb_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductRequest) ProtoMessage() {}

func (x *CheckProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductRequest.ProtoReflect.Descriptor instead.
func (*CheckProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{0}
}

func (x *CheckProductRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

type CheckProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bool          bool                   `protobuf:"varint,1,opt,name=bool,proto3" json:"bool,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductResponse) Reset() {
	*x = CheckProductResponse{}
	mi := &file_pkg_pb_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductResponse) ProtoMessage() {}

func (x *CheckProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductResponse.ProtoReflect.Descriptor instead.
func (*CheckProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{1}
}

func (x *CheckProductResponse) GetBool() bool {
	if x != nil {
		return x.Bool
	}
	return false
}

func (x *CheckProductResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	CategoryID    int64                  `protobuf:"varint,3,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	Stock         int64                  `protobuf:"varint,5,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         float32                `protobuf:"fixed32,6,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_pkg_pb_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{2}
}

func (x *AddProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProductRequest) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *AddProductRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AddProductRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AddProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CategoryID    int64                  `protobuf:"varint,4,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=Price,proto3" json:"Price,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	mi := &file_pkg_pb_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{3}
}

func (x *AddProductResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AddProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProductResponse) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *AddProductResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AddProductResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddProductResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddProductResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductRequest) Reset() {
	*x = ListProductRequest{}
	mi := &file_pkg_pb_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductRequest) ProtoMessage() {}

func (x *ListProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductRequest.ProtoReflect.Descriptor instead.
func (*ListProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ProductDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CategoryID    int64                  `protobuf:"varint,4,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=Price,proto3" json:"Price,omitempty"`
	ProductStatus string                 `protobuf:"bytes,8,opt,name=ProductStatus,proto3" json:"ProductStatus,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDetails) Reset() {
	*x = ProductDetails{}
	mi := &file_pkg_pb_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetails) ProtoMessage() {}

func (x *ProductDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetails.ProtoReflect.Descriptor instead.
func (*ProductDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductDetails) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProductDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductDetails) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductDetails) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *ProductDetails) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ProductDetails) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductDetails) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductDetails) GetProductStatus() string {
	if x != nil {
		return x.ProductStatus
	}
	return ""
}

func (x *ProductDetails) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       []*ProductDetails      `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductResponse) Reset() {
	*x = ListProductResponse{}
	mi := &file_pkg_pb_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductResponse) ProtoMessage() {}

func (x *ListProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductResponse.ProtoReflect.Descriptor instead.
func (*ListProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductResponse) GetDetails() []*ProductDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CategoryID    int64                  `protobuf:"varint,4,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_pkg_pb_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *UpdateProductRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UpdateProductRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	CategoryID    int64                  `protobuf:"varint,4,opt,name=CategoryID,proto3" json:"CategoryID,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Stock         int64                  `protobuf:"varint,6,opt,name=Stock,proto3" json:"Stock,omitempty"`
	Price         float32                `protobuf:"fixed32,7,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_pkg_pb_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UpdateProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductResponse) GetCategoryID() int64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *UpdateProductResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UpdateProductResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_pkg_pb_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_pkg_pb_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetQuantityFromProductIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuantityFromProductIDRequest) Reset() {
	*x = GetQuantityFromProductIDRequest{}
	mi := &file_pkg_pb_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuantityFromProductIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuantityFromProductIDRequest) ProtoMessage() {}

func (x *GetQuantityFromProductIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuantityFromProductIDRequest.ProtoReflect.Descriptor instead.
func (*GetQuantityFromProductIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{11}
}

func (x *GetQuantityFromProductIDRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetQuantityFromProductIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      int64                  `protobuf:"varint,1,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuantityFromProductIDResponse) Reset() {
	*x = GetQuantityFromProductIDResponse{}
	mi := &file_pkg_pb_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuantityFromProductIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuantityFromProductIDResponse) ProtoMessage() {}

func (x *GetQuantityFromProductIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuantityFromProductIDResponse.ProtoReflect.Descriptor instead.
func (*GetQuantityFromProductIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{12}
}

func (x *GetQuantityFromProductIDResponse) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *GetQuantityFromProductIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetPriceofProductFromIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceofProductFromIDRequest) Reset() {
	*x = GetPriceofProductFromIDRequest{}
	mi := &file_pkg_pb_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceofProductFromIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceofProductFromIDRequest) ProtoMessage() {}

func (x *GetPriceofProductFromIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceofProductFromIDRequest.ProtoReflect.Descriptor instead.
func (*GetPriceofProductFromIDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{13}
}

func (x *GetPriceofProductFromIDRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetPriceofProductFromIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int64                  `protobuf:"varint,1,opt,name=Price,proto3" json:"Price,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceofProductFromIDResponse) Reset() {
	*x = GetPriceofProductFromIDResponse{}
	mi := &file_pkg_pb_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceofProductFromIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceofProductFromIDResponse) ProtoMessage() {}

func (x *GetPriceofProductFromIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceofProductFromIDResponse.ProtoReflect.Descriptor instead.
func (*GetPriceofProductFromIDResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{14}
}

func (x *GetPriceofProductFromIDResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetPriceofProductFromIDResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ProductStockMinusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Stock         int64                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductStockMinusRequest) Reset() {
	*x = ProductStockMinusRequest{}
	mi := &file_pkg_pb_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStockMinusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStockMinusRequest) ProtoMessage() {}

func (x *ProductStockMinusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStockMinusRequest.ProtoReflect.Descriptor instead.
func (*ProductStockMinusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{15}
}

func (x *ProductStockMinusRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProductStockMinusRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ProductStockMinusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductStockMinusResponse) Reset() {
	*x = ProductStockMinusResponse{}
	mi := &file_pkg_pb_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStockMinusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStockMinusResponse) ProtoMessage() {}

func (x *ProductStockMinusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStockMinusResponse.ProtoReflect.Descriptor instead.
func (*ProductStockMinusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_product_proto_rawDescGZIP(), []int{16}
}

func (x *ProductStockMinusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pb_product_proto protoreflect.FileDescriptor

const file_pkg_pb_product_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/pb/product.proto\x12\aproduct\"3\n" +
	"\x13CheckProductRequest\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\"@\n" +
	"\x14CheckProductResponse\x12\x12\n" +
	"\x04bool\x18\x01 \x01(\bR\x04bool\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"\xa9\x01\n" +
	"\x11AddProductRequest\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x03 \x01(\x03R\n" +
	"CategoryID\x12\x12\n" +
	"\x04Size\x18\x04 \x01(\x03R\x04Size\x12\x14\n" +
	"\x05Stock\x18\x05 \x01(\x03R\x05Stock\x12\x14\n" +
	"\x05Price\x18\x06 \x01(\x02R\x05Price\"\xd0\x01\n" +
	"\x12AddProductResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x04 \x01(\x03R\n" +
	"CategoryID\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\x03R\x04Size\x12\x14\n" +
	"\x05Stock\x18\x06 \x01(\x03R\x05Stock\x12\x14\n" +
	"\x05Price\x18\a \x01(\x02R\x05Price\x12\x14\n" +
	"\x05Error\x18\b \x01(\tR\x05Error\">\n" +
	"\x12ListProductRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xf2\x01\n" +
	"\x0eProductDetails\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x04 \x01(\x03R\n" +
	"CategoryID\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\x03R\x04Size\x12\x14\n" +
	"\x05Stock\x18\x06 \x01(\x03R\x05Stock\x12\x14\n" +
	"\x05Price\x18\a \x01(\x02R\x05Price\x12$\n" +
	"\rProductStatus\x18\b \x01(\tR\rProductStatus\x12\x14\n" +
	"\x05Error\x18\t \x01(\tR\x05Error\"H\n" +
	"\x13ListProductResponse\x121\n" +
	"\adetails\x18\x01 \x03(\v2\x17.product.ProductDetailsR\adetails\"\xbc\x01\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x04 \x01(\x03R\n" +
	"CategoryID\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\x03R\x04Size\x12\x14\n" +
	"\x05Stock\x18\x06 \x01(\x03R\x05Stock\x12\x14\n" +
	"\x05Price\x18\a \x01(\x02R\x05Price\"\xbd\x01\n" +
	"\x15UpdateProductResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"CategoryID\x18\x04 \x01(\x03R\n" +
	"CategoryID\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\x03R\x04Size\x12\x14\n" +
	"\x05Stock\x18\x06 \x01(\x03R\x05Stock\x12\x14\n" +
	"\x05Price\x18\a \x01(\x02R\x05Price\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"-\n" +
	"\x15DeleteProductResponse\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\"1\n" +
	"\x1fGetQuantityFromProductIDRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"T\n" +
	" GetQuantityFromProductIDResponse\x12\x1a\n" +
	"\bQuantity\x18\x01 \x01(\x03R\bQuantity\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"0\n" +
	"\x1eGetPriceofProductFromIDRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"M\n" +
	"\x1fGetPriceofProductFromIDResponse\x12\x14\n" +
	"\x05Price\x18\x01 \x01(\x03R\x05Price\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"@\n" +
	"\x18ProductStockMinusRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x03R\x05stock\"1\n" +
	"\x19ProductStockMinusResponse\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error2\xd4\x05\n" +
	"\aProduct\x12G\n" +
	"\n" +
	"AddProduct\x12\x1a.product.AddProductRequest\x1a\x1b.product.AddProductResponse\"\x00\x12K\n" +
	"\fListProducts\x12\x1b.product.ListProductRequest\x1a\x1c.product.ListProductResponse\"\x00\x12Q\n" +
	"\x0eUpdateProducts\x12\x1d.product.UpdateProductRequest\x1a\x1e.product.UpdateProductResponse\"\x00\x12P\n" +
	"\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponse\"\x00\x12q\n" +
	"\x18GetQuantityFromProductID\x12(.product.GetQuantityFromProductIDRequest\x1a).product.GetQuantityFromProductIDResponse\"\x00\x12n\n" +
	"\x17GetPriceofProductFromID\x12'.product.GetPriceofProductFromIDRequest\x1a(.product.GetPriceofProductFromIDResponse\"\x00\x12\\\n" +
	"\x11ProductStockMinus\x12!.product.ProductStockMinusRequest\x1a\".product.ProductStockMinusResponse\"\x00\x12M\n" +
	"\fCheckProduct\x12\x1c.product.CheckProductRequest\x1a\x1d.product.CheckProductResponse\"\x00B\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_product_proto_rawDescOnce sync.Once
	file_pkg_pb_product_proto_rawDescData []byte
)

func file_pkg_pb_product_proto_rawDescGZIP() []byte {
	file_pkg_pb_product_proto_rawDescOnce.Do(func() {
		file_pkg_pb_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_product_proto_rawDesc), len(file_pkg_pb_product_proto_rawDesc)))
	})
	return file_pkg_pb_product_proto_rawDescData
}

var file_pkg_pb_product_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_pb_product_proto_goTypes = []any{
	(*CheckProductRequest)(nil),              // 0: product.CheckProductRequest
	(*CheckProductResponse)(nil),             // 1: product.CheckProductResponse
	(*AddProductRequest)(nil),                // 2: product.AddProductRequest
	(*AddProductResponse)(nil),               // 3: product.AddProductResponse
	(*ListProductRequest)(nil),               // 4: product.ListProductRequest
	(*ProductDetails)(nil),                   // 5: product.ProductDetails
	(*ListProductResponse)(nil),              // 6: product.ListProductResponse
	(*UpdateProductRequest)(nil),             // 7: product.UpdateProductRequest
	(*UpdateProductResponse)(nil),            // 8: product.UpdateProductResponse
	(*DeleteProductRequest)(nil),             // 9: product.DeleteProductRequest
	(*DeleteProductResponse)(nil),            // 10: product.DeleteProductResponse
	(*GetQuantityFromProductIDRequest)(nil),  // 11: product.GetQuantityFromProductIDRequest
	(*GetQuantityFromProductIDResponse)(nil), // 12: product.GetQuantityFromProductIDResponse
	(*GetPriceofProductFromIDRequest)(nil),   // 13: product.GetPriceofProductFromIDRequest
	(*GetPriceofProductFromIDResponse)(nil),  // 14: product.GetPriceofProductFromIDResponse
	(*ProductStockMinusRequest)(nil),         // 15: product.ProductStockMinusRequest
	(*ProductStockMinusResponse)(nil),        // 16: product.ProductStockMinusResponse
}
var file_pkg_pb_product_proto_depIdxs = []int32{
	5,  // 0: product.ListProductResponse.details:type_name -> product.ProductDetails
	2,  // 1: product.Product.AddProduct:input_type -> product.AddProductRequest
	4,  // 2: product.Product.ListProducts:input_type -> product.ListProductRequest
	7,  // 3: product.Product.UpdateProducts:input_type -> product.UpdateProductRequest
	9,  // 4: product.Product.DeleteProduct:input_type -> product.DeleteProductRequest
	11, // 5: product.Product.GetQuantityFromProductID:input_type -> product.GetQuantityFromProductIDRequest
	13, // 6: product.Product.GetPriceofProductFromID:input_type -> product.GetPriceofProductFromIDRequest
	15, // 7: product.Product.ProductStockMinus:input_type -> product.ProductStockMinusRequest
	0,  // 8: product.Product.CheckProduct:input_type -> product.CheckProductRequest
	3,  // 9: product.Product.AddProduct:output_type -> product.AddProductResponse
	6,  // 10: product.Product.ListProducts:output_type -> product.ListProductResponse
	8,  // 11: product.Product.UpdateProducts:output_type -> product.UpdateProductResponse
	10, // 12: product.Product.DeleteProduct:output_type -> product.DeleteProductResponse
	12, // 13: product.Product.GetQuantityFromProductID:output_type -> product.GetQuantityFromProductIDResponse
	14, // 14: product.Product.GetPriceofProductFromID:output_type -> product.GetPriceofProductFromIDResponse
	16, // 15: product.Product.ProductStockMinus:output_type -> product.ProductStockMinusResponse
	1,  // 16: product.Product.CheckProduct:output_type -> product.CheckProductResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_pb_product_proto_init() }
func file_pkg_pb_product_proto_init() {
	if File_pkg_pb_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_product_proto_rawDesc), len(file_pkg_pb_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_product_proto_goTypes,
		DependencyIndexes: file_pkg_pb_product_proto_depIdxs,
		MessageInfos:      file_pkg_pb_product_proto_msgTypes,
	}.Build()
	File_pkg_pb_product_proto = out.File
	file_pkg_pb_product_proto_goTypes = nil
	file_pkg_pb_product_proto_depIdxs = nil
}
