// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc1
// source: pkg/pb/cart/cart.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateCartAfterOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ProductID     int64                  `protobuf:"varint,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartAfterOrderRequest) Reset() {
	*x = UpdateCartAfterOrderRequest{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartAfterOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartAfterOrderRequest) ProtoMessage() {}

func (x *UpdateCartAfterOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartAfterOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartAfterOrderRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateCartAfterOrderRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateCartAfterOrderRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *UpdateCartAfterOrderRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateCartAfterOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartAfterOrderResponse) Reset() {
	*x = UpdateCartAfterOrderResponse{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartAfterOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartAfterOrderResponse) ProtoMessage() {}

func (x *UpdateCartAfterOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartAfterOrderResponse.ProtoReflect.Descriptor instead.
func (*UpdateCartAfterOrderResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCartAfterOrderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TotalAmountInCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalAmountInCartRequest) Reset() {
	*x = TotalAmountInCartRequest{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalAmountInCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalAmountInCartRequest) ProtoMessage() {}

func (x *TotalAmountInCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalAmountInCartRequest.ProtoReflect.Descriptor instead.
func (*TotalAmountInCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{2}
}

func (x *TotalAmountInCartRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type TotalAmountInCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          float32                `protobuf:"fixed32,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalAmountInCartResponse) Reset() {
	*x = TotalAmountInCartResponse{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalAmountInCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalAmountInCartResponse) ProtoMessage() {}

func (x *TotalAmountInCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalAmountInCartResponse.ProtoReflect.Descriptor instead.
func (*TotalAmountInCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{3}
}

func (x *TotalAmountInCartResponse) GetData() float32 {
	if x != nil {
		return x.Data
	}
	return 0
}

func (x *TotalAmountInCartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DoesCartExistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoesCartExistRequest) Reset() {
	*x = DoesCartExistRequest{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoesCartExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoesCartExistRequest) ProtoMessage() {}

func (x *DoesCartExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoesCartExistRequest.ProtoReflect.Descriptor instead.
func (*DoesCartExistRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{4}
}

func (x *DoesCartExistRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type DoesCartExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          bool                   `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoesCartExistResponse) Reset() {
	*x = DoesCartExistResponse{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoesCartExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoesCartExistResponse) ProtoMessage() {}

func (x *DoesCartExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoesCartExistResponse.ProtoReflect.Descriptor instead.
func (*DoesCartExistResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{5}
}

func (x *DoesCartExistResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

func (x *DoesCartExistResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{6}
}

func (x *AddToCartRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *AddToCartRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AddToCartRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CartDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity      float32                `protobuf:"fixed32,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,3,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartDetails) Reset() {
	*x = CartDetails{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartDetails) ProtoMessage() {}

func (x *CartDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartDetails.ProtoReflect.Descriptor instead.
func (*CartDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{7}
}

func (x *CartDetails) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *CartDetails) GetQuantity() float32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartDetails) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type AddToCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float32                `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Cart          []*CartDetails         `protobuf:"bytes,2,rep,name=cart,proto3" json:"cart,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartResponse) Reset() {
	*x = AddToCartResponse{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartResponse) ProtoMessage() {}

func (x *AddToCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartResponse.ProtoReflect.Descriptor instead.
func (*AddToCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{8}
}

func (x *AddToCartResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddToCartResponse) GetCart() []*CartDetails {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *AddToCartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{9}
}

func (x *GetCartRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float32                `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Cart          []*CartDetails         `protobuf:"bytes,2,rep,name=cart,proto3" json:"cart,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{10}
}

func (x *GetCartResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetCartResponse) GetCart() []*CartDetails {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *GetCartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAllItemsFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsFromCartRequest) Reset() {
	*x = GetAllItemsFromCartRequest{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsFromCartRequest) ProtoMessage() {}

func (x *GetAllItemsFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsFromCartRequest.ProtoReflect.Descriptor instead.
func (*GetAllItemsFromCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllItemsFromCartRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetAllItemsFromCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          []*CartDetails         `protobuf:"bytes,1,rep,name=cart,proto3" json:"cart,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsFromCartResponse) Reset() {
	*x = GetAllItemsFromCartResponse{}
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsFromCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsFromCartResponse) ProtoMessage() {}

func (x *GetAllItemsFromCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_cart_cart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsFromCartResponse.ProtoReflect.Descriptor instead.
func (*GetAllItemsFromCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_cart_cart_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllItemsFromCartResponse) GetCart() []*CartDetails {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *GetAllItemsFromCartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pb_cart_cart_proto protoreflect.FileDescriptor

const file_pkg_pb_cart_cart_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/pb/cart/cart.proto\x12\x04cart\"o\n" +
	"\x1bUpdateCartAfterOrderRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x1c\n" +
	"\tproductID\x18\x02 \x01(\x03R\tproductID\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"4\n" +
	"\x1cUpdateCartAfterOrderResponse\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\"2\n" +
	"\x18TotalAmountInCartRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\"E\n" +
	"\x19TotalAmountInCartResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x02R\x04data\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\".\n" +
	"\x14DoesCartExistRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\"A\n" +
	"\x15DoesCartExistResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\bR\x04data\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\"d\n" +
	"\x10AddToCartRequest\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\x03R\tproductID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\"g\n" +
	"\vCartDetails\x12\x1c\n" +
	"\tproductID\x18\x01 \x01(\x03R\tproductID\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\x02R\bQuantity\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x03 \x01(\x02R\n" +
	"totalPrice\"f\n" +
	"\x11AddToCartResponse\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x02R\x05price\x12%\n" +
	"\x04cart\x18\x02 \x03(\v2\x11.cart.CartDetailsR\x04cart\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\"(\n" +
	"\x0eGetCartRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\"d\n" +
	"\x0fGetCartResponse\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x02R\x05price\x12%\n" +
	"\x04cart\x18\x02 \x03(\v2\x11.cart.CartDetailsR\x04cart\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\"4\n" +
	"\x1aGetAllItemsFromCartRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\"Z\n" +
	"\x1bGetAllItemsFromCartResponse\x12%\n" +
	"\x04cart\x18\x01 \x03(\v2\x11.cart.CartDetailsR\x04cart\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error2\xe3\x03\n" +
	"\x04Cart\x12>\n" +
	"\tAddToCart\x12\x16.cart.AddToCartRequest\x1a\x17.cart.AddToCartResponse\"\x00\x128\n" +
	"\aGetCart\x12\x14.cart.GetCartRequest\x1a\x15.cart.GetCartResponse\"\x00\x12\\\n" +
	"\x13GetAllItemsFromCart\x12 .cart.GetAllItemsFromCartRequest\x1a!.cart.GetAllItemsFromCartResponse\"\x00\x12J\n" +
	"\rDoesCartExist\x12\x1a.cart.DoesCartExistRequest\x1a\x1b.cart.DoesCartExistResponse\"\x00\x12V\n" +
	"\x11TotalAmountInCart\x12\x1e.cart.TotalAmountInCartRequest\x1a\x1f.cart.TotalAmountInCartResponse\"\x00\x12_\n" +
	"\x14UpdateCartAfterOrder\x12!.cart.UpdateCartAfterOrderRequest\x1a\".cart.UpdateCartAfterOrderResponse\"\x00B\x0fZ\r./pkg/pb/cartb\x06proto3"

var (
	file_pkg_pb_cart_cart_proto_rawDescOnce sync.Once
	file_pkg_pb_cart_cart_proto_rawDescData []byte
)

func file_pkg_pb_cart_cart_proto_rawDescGZIP() []byte {
	file_pkg_pb_cart_cart_proto_rawDescOnce.Do(func() {
		file_pkg_pb_cart_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_cart_cart_proto_rawDesc), len(file_pkg_pb_cart_cart_proto_rawDesc)))
	})
	return file_pkg_pb_cart_cart_proto_rawDescData
}

var file_pkg_pb_cart_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_pb_cart_cart_proto_goTypes = []any{
	(*UpdateCartAfterOrderRequest)(nil),  // 0: cart.UpdateCartAfterOrderRequest
	(*UpdateCartAfterOrderResponse)(nil), // 1: cart.UpdateCartAfterOrderResponse
	(*TotalAmountInCartRequest)(nil),     // 2: cart.TotalAmountInCartRequest
	(*TotalAmountInCartResponse)(nil),    // 3: cart.TotalAmountInCartResponse
	(*DoesCartExistRequest)(nil),         // 4: cart.DoesCartExistRequest
	(*DoesCartExistResponse)(nil),        // 5: cart.DoesCartExistResponse
	(*AddToCartRequest)(nil),             // 6: cart.AddToCartRequest
	(*CartDetails)(nil),                  // 7: cart.CartDetails
	(*AddToCartResponse)(nil),            // 8: cart.AddToCartResponse
	(*GetCartRequest)(nil),               // 9: cart.GetCartRequest
	(*GetCartResponse)(nil),              // 10: cart.GetCartResponse
	(*GetAllItemsFromCartRequest)(nil),   // 11: cart.GetAllItemsFromCartRequest
	(*GetAllItemsFromCartResponse)(nil),  // 12: cart.GetAllItemsFromCartResponse
}
var file_pkg_pb_cart_cart_proto_depIdxs = []int32{
	7,  // 0: cart.AddToCartResponse.cart:type_name -> cart.CartDetails
	7,  // 1: cart.GetCartResponse.cart:type_name -> cart.CartDetails
	7,  // 2: cart.GetAllItemsFromCartResponse.cart:type_name -> cart.CartDetails
	6,  // 3: cart.Cart.AddToCart:input_type -> cart.AddToCartRequest
	9,  // 4: cart.Cart.GetCart:input_type -> cart.GetCartRequest
	11, // 5: cart.Cart.GetAllItemsFromCart:input_type -> cart.GetAllItemsFromCartRequest
	4,  // 6: cart.Cart.DoesCartExist:input_type -> cart.DoesCartExistRequest
	2,  // 7: cart.Cart.TotalAmountInCart:input_type -> cart.TotalAmountInCartRequest
	0,  // 8: cart.Cart.UpdateCartAfterOrder:input_type -> cart.UpdateCartAfterOrderRequest
	8,  // 9: cart.Cart.AddToCart:output_type -> cart.AddToCartResponse
	10, // 10: cart.Cart.GetCart:output_type -> cart.GetCartResponse
	12, // 11: cart.Cart.GetAllItemsFromCart:output_type -> cart.GetAllItemsFromCartResponse
	5,  // 12: cart.Cart.DoesCartExist:output_type -> cart.DoesCartExistResponse
	3,  // 13: cart.Cart.TotalAmountInCart:output_type -> cart.TotalAmountInCartResponse
	1,  // 14: cart.Cart.UpdateCartAfterOrder:output_type -> cart.UpdateCartAfterOrderResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_pb_cart_cart_proto_init() }
func file_pkg_pb_cart_cart_proto_init() {
	if File_pkg_pb_cart_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_cart_cart_proto_rawDesc), len(file_pkg_pb_cart_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_cart_cart_proto_goTypes,
		DependencyIndexes: file_pkg_pb_cart_cart_proto_depIdxs,
		MessageInfos:      file_pkg_pb_cart_cart_proto_msgTypes,
	}.Build()
	File_pkg_pb_cart_cart_proto = out.File
	file_pkg_pb_cart_cart_proto_goTypes = nil
	file_pkg_pb_cart_cart_proto_depIdxs = nil
}
