// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc1
// source: pkg/pb/order/order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressID     int64                  `protobuf:"varint,1,opt,name=AddressID,proto3" json:"AddressID,omitempty"`
	PaymentID     int64                  `protobuf:"varint,2,opt,name=PaymentID,proto3" json:"PaymentID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_pkg_pb_order_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetAddressID() int64 {
	if x != nil {
		return x.AddressID
	}
	return 0
}

func (x *OrderItem) GetPaymentID() int64 {
	if x != nil {
		return x.PaymentID
	}
	return 0
}

type OrderItemsFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderFromCart *OrderItem             `protobuf:"bytes,1,opt,name=OrderFromCart,proto3" json:"OrderFromCart,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemsFromCartRequest) Reset() {
	*x = OrderItemsFromCartRequest{}
	mi := &file_pkg_pb_order_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemsFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemsFromCartRequest) ProtoMessage() {}

func (x *OrderItemsFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemsFromCartRequest.ProtoReflect.Descriptor instead.
func (*OrderItemsFromCartRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItemsFromCartRequest) GetOrderFromCart() *OrderItem {
	if x != nil {
		return x.OrderFromCart
	}
	return nil
}

func (x *OrderItemsFromCartRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type OrderItemsFromCartResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderID        int64                  `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	ShipmentStatus string                 `protobuf:"bytes,2,opt,name=ShipmentStatus,proto3" json:"ShipmentStatus,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderItemsFromCartResponse) Reset() {
	*x = OrderItemsFromCartResponse{}
	mi := &file_pkg_pb_order_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemsFromCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemsFromCartResponse) ProtoMessage() {}

func (x *OrderItemsFromCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemsFromCartResponse.ProtoReflect.Descriptor instead.
func (*OrderItemsFromCartResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItemsFromCartResponse) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *OrderItemsFromCartResponse) GetShipmentStatus() string {
	if x != nil {
		return x.ShipmentStatus
	}
	return ""
}

func (x *OrderItemsFromCartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetOrderDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailsRequest) Reset() {
	*x = GetOrderDetailsRequest{}
	mi := &file_pkg_pb_order_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailsRequest) ProtoMessage() {}

func (x *GetOrderDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderDetailsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderDetailsRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type OrderDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderID        int64                  `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Price          float32                `protobuf:"fixed32,2,opt,name=Price,proto3" json:"Price,omitempty"`
	Shipmentstatus string                 `protobuf:"bytes,3,opt,name=Shipmentstatus,proto3" json:"Shipmentstatus,omitempty"`
	Paymentstatus  string                 `protobuf:"bytes,4,opt,name=Paymentstatus,proto3" json:"Paymentstatus,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderDetails) Reset() {
	*x = OrderDetails{}
	mi := &file_pkg_pb_order_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetails) ProtoMessage() {}

func (x *OrderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetails.ProtoReflect.Descriptor instead.
func (*OrderDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderDetails) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *OrderDetails) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderDetails) GetShipmentstatus() string {
	if x != nil {
		return x.Shipmentstatus
	}
	return ""
}

func (x *OrderDetails) GetPaymentstatus() string {
	if x != nil {
		return x.Paymentstatus
	}
	return ""
}

type OrderProductDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     int64                  `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProductDetails) Reset() {
	*x = OrderProductDetails{}
	mi := &file_pkg_pb_order_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProductDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProductDetails) ProtoMessage() {}

func (x *OrderProductDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProductDetails.ProtoReflect.Descriptor instead.
func (*OrderProductDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderProductDetails) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *OrderProductDetails) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderProductDetails) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type FullOrderDetails struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderDetails        *OrderDetails          `protobuf:"bytes,1,opt,name=orderDetails,proto3" json:"orderDetails,omitempty"`
	OrderProductDetails []*OrderProductDetails `protobuf:"bytes,2,rep,name=OrderProductDetails,proto3" json:"OrderProductDetails,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FullOrderDetails) Reset() {
	*x = FullOrderDetails{}
	mi := &file_pkg_pb_order_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullOrderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullOrderDetails) ProtoMessage() {}

func (x *FullOrderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullOrderDetails.ProtoReflect.Descriptor instead.
func (*FullOrderDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{6}
}

func (x *FullOrderDetails) GetOrderDetails() *OrderDetails {
	if x != nil {
		return x.OrderDetails
	}
	return nil
}

func (x *FullOrderDetails) GetOrderProductDetails() []*OrderProductDetails {
	if x != nil {
		return x.OrderProductDetails
	}
	return nil
}

type GetOrderDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       []*FullOrderDetails    `protobuf:"bytes,1,rep,name=Details,proto3" json:"Details,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailsResponse) Reset() {
	*x = GetOrderDetailsResponse{}
	mi := &file_pkg_pb_order_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailsResponse) ProtoMessage() {}

func (x *GetOrderDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_order_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderDetailsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_order_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderDetailsResponse) GetDetails() []*FullOrderDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *GetOrderDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pb_order_order_proto protoreflect.FileDescriptor

const file_pkg_pb_order_order_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/pb/order/order.proto\x12\x05order\"G\n" +
	"\tOrderItem\x12\x1c\n" +
	"\tAddressID\x18\x01 \x01(\x03R\tAddressID\x12\x1c\n" +
	"\tPaymentID\x18\x02 \x01(\x03R\tPaymentID\"k\n" +
	"\x19OrderItemsFromCartRequest\x126\n" +
	"\rOrderFromCart\x18\x01 \x01(\v2\x10.order.OrderItemR\rOrderFromCart\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\x03R\x06UserID\"t\n" +
	"\x1aOrderItemsFromCartResponse\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\x03R\aOrderID\x12&\n" +
	"\x0eShipmentStatus\x18\x02 \x01(\tR\x0eShipmentStatus\x12\x14\n" +
	"\x05Error\x18\x03 \x01(\tR\x05Error\"0\n" +
	"\x16GetOrderDetailsRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x03R\x06UserID\"\x8c\x01\n" +
	"\fOrderDetails\x12\x18\n" +
	"\aOrderID\x18\x01 \x01(\x03R\aOrderID\x12\x14\n" +
	"\x05Price\x18\x02 \x01(\x02R\x05Price\x12&\n" +
	"\x0eShipmentstatus\x18\x03 \x01(\tR\x0eShipmentstatus\x12$\n" +
	"\rPaymentstatus\x18\x04 \x01(\tR\rPaymentstatus\"e\n" +
	"\x13OrderProductDetails\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\x03R\tProductID\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\x03R\bQuantity\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x02R\x05Price\"\x99\x01\n" +
	"\x10FullOrderDetails\x127\n" +
	"\forderDetails\x18\x01 \x01(\v2\x13.order.OrderDetailsR\forderDetails\x12L\n" +
	"\x13OrderProductDetails\x18\x02 \x03(\v2\x1a.order.OrderProductDetailsR\x13OrderProductDetails\"b\n" +
	"\x17GetOrderDetailsResponse\x121\n" +
	"\aDetails\x18\x01 \x03(\v2\x17.order.FullOrderDetailsR\aDetails\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error2\xb8\x01\n" +
	"\x05Order\x12[\n" +
	"\x12OrderItemsFromCart\x12 .order.OrderItemsFromCartRequest\x1a!.order.OrderItemsFromCartResponse\"\x00\x12R\n" +
	"\x0fGetOrderDetails\x12\x1d.order.GetOrderDetailsRequest\x1a\x1e.order.GetOrderDetailsResponse\"\x00B\x10Z\x0e./pkg/pb/orderb\x06proto3"

var (
	file_pkg_pb_order_order_proto_rawDescOnce sync.Once
	file_pkg_pb_order_order_proto_rawDescData []byte
)

func file_pkg_pb_order_order_proto_rawDescGZIP() []byte {
	file_pkg_pb_order_order_proto_rawDescOnce.Do(func() {
		file_pkg_pb_order_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_order_order_proto_rawDesc), len(file_pkg_pb_order_order_proto_rawDesc)))
	})
	return file_pkg_pb_order_order_proto_rawDescData
}

var file_pkg_pb_order_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_pb_order_order_proto_goTypes = []any{
	(*OrderItem)(nil),                  // 0: order.OrderItem
	(*OrderItemsFromCartRequest)(nil),  // 1: order.OrderItemsFromCartRequest
	(*OrderItemsFromCartResponse)(nil), // 2: order.OrderItemsFromCartResponse
	(*GetOrderDetailsRequest)(nil),     // 3: order.GetOrderDetailsRequest
	(*OrderDetails)(nil),               // 4: order.OrderDetails
	(*OrderProductDetails)(nil),        // 5: order.OrderProductDetails
	(*FullOrderDetails)(nil),           // 6: order.FullOrderDetails
	(*GetOrderDetailsResponse)(nil),    // 7: order.GetOrderDetailsResponse
}
var file_pkg_pb_order_order_proto_depIdxs = []int32{
	0, // 0: order.OrderItemsFromCartRequest.OrderFromCart:type_name -> order.OrderItem
	4, // 1: order.FullOrderDetails.orderDetails:type_name -> order.OrderDetails
	5, // 2: order.FullOrderDetails.OrderProductDetails:type_name -> order.OrderProductDetails
	6, // 3: order.GetOrderDetailsResponse.Details:type_name -> order.FullOrderDetails
	1, // 4: order.Order.OrderItemsFromCart:input_type -> order.OrderItemsFromCartRequest
	3, // 5: order.Order.GetOrderDetails:input_type -> order.GetOrderDetailsRequest
	2, // 6: order.Order.OrderItemsFromCart:output_type -> order.OrderItemsFromCartResponse
	7, // 7: order.Order.GetOrderDetails:output_type -> order.GetOrderDetailsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_pb_order_order_proto_init() }
func file_pkg_pb_order_order_proto_init() {
	if File_pkg_pb_order_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_order_order_proto_rawDesc), len(file_pkg_pb_order_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_order_order_proto_goTypes,
		DependencyIndexes: file_pkg_pb_order_order_proto_depIdxs,
		MessageInfos:      file_pkg_pb_order_order_proto_msgTypes,
	}.Build()
	File_pkg_pb_order_order_proto = out.File
	file_pkg_pb_order_order_proto_goTypes = nil
	file_pkg_pb_order_order_proto_depIdxs = nil
}
