// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc1
// source: pkg/pb/address.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address-related messages
type AddressDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	District      string                 `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	ZipCode       string                 `protobuf:"bytes,7,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressDetails) Reset() {
	*x = AddressDetails{}
	mi := &file_pkg_pb_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressDetails) ProtoMessage() {}

func (x *AddressDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressDetails.ProtoReflect.Descriptor instead.
func (*AddressDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_address_proto_rawDescGZIP(), []int{0}
}

func (x *AddressDetails) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressDetails) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddressDetails) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *AddressDetails) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressDetails) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AddressDetails) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddressDetails) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *AddressDetails) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type AddAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	District      string                 `protobuf:"bytes,5,opt,name=district,proto3" json:"district,omitempty"`
	ZipCode       string                 `protobuf:"bytes,6,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAddressRequest) Reset() {
	*x = AddAddressRequest{}
	mi := &file_pkg_pb_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddressRequest) ProtoMessage() {}

func (x *AddAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddressRequest.ProtoReflect.Descriptor instead.
func (*AddAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_address_proto_rawDescGZIP(), []int{1}
}

func (x *AddAddressRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *AddAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AddAddressRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddAddressRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *AddAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type AddAddressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	AddressDetails *AddressDetails        `protobuf:"bytes,2,opt,name=addressDetails,proto3" json:"addressDetails,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddAddressResponse) Reset() {
	*x = AddAddressResponse{}
	mi := &file_pkg_pb_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddressResponse) ProtoMessage() {}

func (x *AddAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddressResponse.ProtoReflect.Descriptor instead.
func (*AddAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_address_proto_rawDescGZIP(), []int{2}
}

func (x *AddAddressResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddAddressResponse) GetAddressDetails() *AddressDetails {
	if x != nil {
		return x.AddressDetails
	}
	return nil
}

type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_pkg_pb_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_address_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddressRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAddressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	AddressDetails *AddressDetails        `protobuf:"bytes,2,opt,name=addressDetails,proto3" json:"addressDetails,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAddressResponse) Reset() {
	*x = GetAddressResponse{}
	mi := &file_pkg_pb_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressResponse) ProtoMessage() {}

func (x *GetAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressResponse.ProtoReflect.Descriptor instead.
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_address_proto_rawDescGZIP(), []int{4}
}

func (x *GetAddressResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAddressResponse) GetAddressDetails() *AddressDetails {
	if x != nil {
		return x.AddressDetails
	}
	return nil
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	District      string                 `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	ZipCode       string                 `protobuf:"bytes,7,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_pkg_pb_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_address_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAddressRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAddressRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UpdateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateAddressRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UpdateAddressRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *UpdateAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type UpdateAddressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	AddressDetails *AddressDetails        `protobuf:"bytes,2,opt,name=addressDetails,proto3" json:"addressDetails,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAddressResponse) Reset() {
	*x = UpdateAddressResponse{}
	mi := &file_pkg_pb_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressResponse) ProtoMessage() {}

func (x *UpdateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressResponse.ProtoReflect.Descriptor instead.
func (*UpdateAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_address_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAddressResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateAddressResponse) GetAddressDetails() *AddressDetails {
	if x != nil {
		return x.AddressDetails
	}
	return nil
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_pkg_pb_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_address_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAddressRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressResponse) Reset() {
	*x = DeleteAddressResponse{}
	mi := &file_pkg_pb_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResponse) ProtoMessage() {}

func (x *DeleteAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_address_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAddressResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_pkg_pb_address_proto protoreflect.FileDescriptor

const file_pkg_pb_address_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/pb/address.proto\x12\aaddress\"\xcc\x01\n" +
	"\x0eAddressDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1a\n" +
	"\bdistrict\x18\x06 \x01(\tR\bdistrict\x12\x19\n" +
	"\bzip_code\x18\a \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\"\xbf\x01\n" +
	"\x11AddAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1a\n" +
	"\bdistrict\x18\x05 \x01(\tR\bdistrict\x12\x19\n" +
	"\bzip_code\x18\x06 \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\"m\n" +
	"\x12AddAddressResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12?\n" +
	"\x0eaddressDetails\x18\x02 \x01(\v2\x17.address.AddressDetailsR\x0eaddressDetails\"#\n" +
	"\x11GetAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"m\n" +
	"\x12GetAddressResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12?\n" +
	"\x0eaddressDetails\x18\x02 \x01(\v2\x17.address.AddressDetailsR\x0eaddressDetails\"\xd2\x01\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1a\n" +
	"\bdistrict\x18\x06 \x01(\tR\bdistrict\x12\x19\n" +
	"\bzip_code\x18\a \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\"p\n" +
	"\x15UpdateAddressResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12?\n" +
	"\x0eaddressDetails\x18\x02 \x01(\v2\x17.address.AddressDetailsR\x0eaddressDetails\"&\n" +
	"\x14DeleteAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"/\n" +
	"\x15DeleteAddressResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status2\xc3\x02\n" +
	"\aAddress\x12G\n" +
	"\n" +
	"AddAddress\x12\x1a.address.AddAddressRequest\x1a\x1b.address.AddAddressResponse\"\x00\x12K\n" +
	"\x0eGetAddressByID\x12\x1a.address.GetAddressRequest\x1a\x1b.address.GetAddressResponse\"\x00\x12P\n" +
	"\rUpdateAddress\x12\x1d.address.UpdateAddressRequest\x1a\x1e.address.UpdateAddressResponse\"\x00\x12P\n" +
	"\rDeleteAddress\x12\x1d.address.DeleteAddressRequest\x1a\x1e.address.DeleteAddressResponse\"\x00B\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_address_proto_rawDescOnce sync.Once
	file_pkg_pb_address_proto_rawDescData []byte
)

func file_pkg_pb_address_proto_rawDescGZIP() []byte {
	file_pkg_pb_address_proto_rawDescOnce.Do(func() {
		file_pkg_pb_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_address_proto_rawDesc), len(file_pkg_pb_address_proto_rawDesc)))
	})
	return file_pkg_pb_address_proto_rawDescData
}

var file_pkg_pb_address_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_pb_address_proto_goTypes = []any{
	(*AddressDetails)(nil),        // 0: address.AddressDetails
	(*AddAddressRequest)(nil),     // 1: address.AddAddressRequest
	(*AddAddressResponse)(nil),    // 2: address.AddAddressResponse
	(*GetAddressRequest)(nil),     // 3: address.GetAddressRequest
	(*GetAddressResponse)(nil),    // 4: address.GetAddressResponse
	(*UpdateAddressRequest)(nil),  // 5: address.UpdateAddressRequest
	(*UpdateAddressResponse)(nil), // 6: address.UpdateAddressResponse
	(*DeleteAddressRequest)(nil),  // 7: address.DeleteAddressRequest
	(*DeleteAddressResponse)(nil), // 8: address.DeleteAddressResponse
}
var file_pkg_pb_address_proto_depIdxs = []int32{
	0, // 0: address.AddAddressResponse.addressDetails:type_name -> address.AddressDetails
	0, // 1: address.GetAddressResponse.addressDetails:type_name -> address.AddressDetails
	0, // 2: address.UpdateAddressResponse.addressDetails:type_name -> address.AddressDetails
	1, // 3: address.Address.AddAddress:input_type -> address.AddAddressRequest
	3, // 4: address.Address.GetAddressByID:input_type -> address.GetAddressRequest
	5, // 5: address.Address.UpdateAddress:input_type -> address.UpdateAddressRequest
	7, // 6: address.Address.DeleteAddress:input_type -> address.DeleteAddressRequest
	2, // 7: address.Address.AddAddress:output_type -> address.AddAddressResponse
	4, // 8: address.Address.GetAddressByID:output_type -> address.GetAddressResponse
	6, // 9: address.Address.UpdateAddress:output_type -> address.UpdateAddressResponse
	8, // 10: address.Address.DeleteAddress:output_type -> address.DeleteAddressResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_pb_address_proto_init() }
func file_pkg_pb_address_proto_init() {
	if File_pkg_pb_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_address_proto_rawDesc), len(file_pkg_pb_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_address_proto_goTypes,
		DependencyIndexes: file_pkg_pb_address_proto_depIdxs,
		MessageInfos:      file_pkg_pb_address_proto_msgTypes,
	}.Build()
	File_pkg_pb_address_proto = out.File
	file_pkg_pb_address_proto_goTypes = nil
	file_pkg_pb_address_proto_depIdxs = nil
}
